Add test action creator
isdi-coders-2022/Nigromanticas-Temibles-202209-bcn pull request #10
Opened 2022-10-24 18:36 UTC by Champurias

2022-10-24 18:36 UTC, mireiarull approved these changes

2022-10-24 18:37 UTC, Tutitoos approved these changes

2022-10-24 20:18 UTC, Rotciv86 requested changes
El test lo entiendo y esta perfecto. Felicidades David!!
Y además añadiría que hay que poner en mayúsculas el "When" y el "Then" (Mario lo quiere asín 😅).
Y los textos del segundo describe y el test no los acabo de ver. En el test es solo una errata, "a type of"

2022-10-25 07:43 UTC, mireiarull approved these changes

2022-10-25 07:43 UTC, Rotciv86 approved these changes

2022-10-25 08:04 UTC, merged